<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2022-11-29">

<title>PCA (principal component analysis)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<script src="index_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="index_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="index_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="toc-section-number">1</span>  Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="toc-section-number">2</span>  Methods</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a></li>
  <li><a href="#sample-data" id="toc-sample-data" class="nav-link" data-scroll-target="#sample-data">Sample Data</a></li>
  <li><a href="#equations" id="toc-equations" class="nav-link" data-scroll-target="#equations">Equations</a></li>
  </ul></li>
  <li><a href="#analysis-and-results" id="toc-analysis-and-results" class="nav-link" data-scroll-target="#analysis-and-results"><span class="toc-section-number">3</span>  Analysis and Results</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#pca" id="toc-pca" class="nav-link" data-scroll-target="#pca">PCA</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="toc-section-number">4</span>  Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="toc-section-number">5</span>  References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PCA (principal component analysis)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Brandy Carr, Lee, Tavish </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 29, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p><a href="https://bjcarr08.github.io/STA6257_Project_PCA/">Website</a></p>
<p><a href="slides.html">Slides</a></p>
<style>
 .title {
    color: #191970;    
  }
 .subtitle {
    color: #191970;
  }
  .author {
    color: #191970;
}
 body {
    color: #8B814C;
    background-color: #FAFAF5;
    font-size: 12pt;
    font-weight: lighter;
  }
  h1 {
    color: #191970;
    font-weight: bold;
}
  h2 {
    color: #191970;  
}
  h3 {
    color: #191970;  
}
  h4 {
    color: #191970;  
}
 .bibliography {
    background-color: #FAFAF5;
}
 .reference-section-title {
    color: #191970;
}
</style>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>Principal Component Analysis (PCA) is an unsupervised machine learning method (<a href="#fig-machineLearning">Figure&nbsp;1</a>) that can be used as the first step in data analysis. The main goal of PCA is to reduce the number of dimensions/features while retaining most of the original variability. Reducing the number of features makes it easier to graphically visualize hidden patterns in the data, it’s also useful when encountering a high number of predictor variables or highly correlated variables when running a regression model <span class="citation" data-cites="lang2021applied">(<a href="#ref-lang2021applied" role="doc-biblioref">Lang and Qiu 2021</a>)</span>. After the data has been transformed with PCA, using a clustering algorithm such as k-means can provide additional power to the analysis of high dimensional data containing linearly correlated features <span class="citation" data-cites="Alkha">(<a href="#ref-Alkha" role="doc-biblioref">Alkhayrat, Aljnidi, and Aljoumaa 2020</a>)</span>.</p>
<p>The most important use of PCA is to represent a multivariate data table as smaller set of variables (summary indices) to observe hidden trends, jumps, clusters, patterns and outliers.</p>
<p>PCA is a broadly used statistical method whose use stretches across many scientific disciplines, and in turn many different adaptations of PCA have been developed based on the variation in goals and data types associated with each respective discipline. PCA was developed first by Pearson (1901) and Hotelling (1933) <span class="citation" data-cites="Camargo">(<a href="#ref-Camargo" role="doc-biblioref">A 2022</a>)</span>. This technique transforms some number of possibly correlated variables into a smaller number of variables, the variables in this smaller matrix are referred to as the Principal Components (PC). This is achieved using a vector space transform. By mathematical projection we can interpret the original data set with just a few variables, namely the principal components achieved through calculation. Reducing dimension size in large data sets makes it easier to spot trends, patterns, and outliers in data where that information would have previously been hidden by the size of data (Richardson). The information being preserved in the process of reduction is the variability in the data (i.e.&nbsp;the statistical information present in the data). In order to preserve as much variability as possible we should “…find new variables that are linear functions of those in the original data set, that successively maximize variance and that are uncorrelated with each other” <span class="citation" data-cites="Jolliffe">(<a href="#ref-Jolliffe" role="doc-biblioref">Jolliffe IT 2016</a>)</span>. PCA assumes no distribution in data in a descriptive context, one of it’s key features that makes it so widely adaptive as an exploratory method across disciplines and data types <span class="citation" data-cites="Jolliffe">(<a href="#ref-Jolliffe" role="doc-biblioref">Jolliffe IT 2016</a>)</span>.</p>
<p>To lists all of PCA’s applications would be tedious and excessive, but some examples where PCA has been used is in image analysis, analysis of web data, and cyber security analysis. Essentially anywhere that large data sets are found PCA can be used to aid in discovering trends amongst the variables of that data. PCA can also be useful when studying mental disorders, data consisting of symptoms and the connections between them. When many symptoms are being observed, it can be difficult to visually represent the connections between them, both the strength of the connections and the proximity to each other. Plotting using the first 2 principal components allows for the placement on the x or y axis to become interpretable, that is, observations far left differ in some dimension (the first principal component) compared to ones far right. The same can be said in the y direction <span class="citation" data-cites="Jones">(<a href="#ref-Jones" role="doc-biblioref">Jones, Mair, and McNally 2018</a>)</span>. PCA also aids in recognizing microanerysm in medicine and how groundbreaking has been critical for diagnosis and treatment of Diabetic retinopathy <span class="citation" data-cites="Cao2018">(<a href="#ref-Cao2018" role="doc-biblioref">Cao et al. 2018</a>)</span>. Research papers show a framework for coronary artery disease risk assessment in intravascular ultrasound. The paper reflects on a novel strategy for risk stratification based on plaque morphology embedded with principal component analysis (PCA) for plaque feature dimensionality reduction and dominant feature selection technique<span class="citation" data-cites="Gorg2021">(<a href="#ref-Gorg2021" role="doc-biblioref">Gorgoglione et al. 2021</a>)</span>. Camargo identified that the best way to compare and evaluate facial recognition results with speed and accuracy is with PCA (Principal Component Analysis), alongside Support Vector Machine (SVM) methods <span class="citation" data-cites="Camargo">(<a href="#ref-Camargo" role="doc-biblioref">A 2022</a>)</span>.</p>
<p>Taking a look into a real world example, say we have a dataset consisting of 1,000 students with exam scores from 7 different courses: Advanced Statistics, Probability Theory, Intro to Dance, World Religions, and Religion in America. We could group Advanced Statistics and Probability Theory into a new variable called Stats, group World Religions and Religion in America into a new variable Religion, and keep Intro to Dance by itself. We have Reduced the data set from 7 variables to 3 without much loss in variation. This is the main concept behind PCA except variables are not manually regrouped but instead the new variables (principal components) are derived from certain linear combinations of the original variables <span class="citation" data-cites="lang2021applied">(<a href="#ref-lang2021applied" role="doc-biblioref">Lang and Qiu 2021</a>)</span>.</p>
<div id="fig-machineLearning" class="quarto-figure quarto-figure-center">
<figure class="figure">
<p></p><figcaption class="figure-caption">Figure&nbsp;1: Machine Learning</figcaption><p></p>
<p><img src="index_files/figure-html/machineLearning_fig1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</section>
<section id="methods" class="level2" data-number="2">
<h2 data-number="2" data-anchor-id="methods"><span class="header-section-number">2</span> Methods</h2>
<p>PCA forms the basis of multivariate data analysis based on projection methods. The variability in the original (correlated) variables will be explained through a smaller (uncorrelated) set of new variables i.e.&nbsp;the principal components (PC’s). PCA results depend on the scale or units of the variables so, for unscaled data, calculations should either be preformed on the correlation matrix (instead of the covariance matrix) or the data should be standardized with mean 0 and variance 1 (z scores) <span class="citation" data-cites="lang2021applied">(<a href="#ref-lang2021applied" role="doc-biblioref">Lang and Qiu 2021</a>)</span>. Firstly, when performing PCA, a new set of orthogonal coordinate axes are identified from the original data set, which is accomplished by finding the direction of maximal variance through each dimension. This is equivalent to using the least squares method to find the line of best fit. This new axis is the first principal component of the data set. Next we use orthogonal projection to project the coordinates onto the new axis. Once this is done we obtain a second principal component (and principal coordinate axis) by finding the direction of the second largest variance in the data, this axis is orthogonal to our first PC. These two PCs define a plane onto which we can project further coordinates onto (Richardson).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource default number-lines code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1"></a>%%{init: {'theme': 'base', 'themeVariables': { 'background': '#FAFAF5', 'primaryColor': '#EAEAD6', 'nodeBorder': '#8B814C', 'lineColor': '#8B814C', 'primaryTextColor': '#191970', 'textColor': '#191970', 'fontSize': '12px', 'width': '100%'}}}%%</span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a>flowchart LR</span>
<span id="cb1-4"><a href="#cb1-4"></a>A[(Clean&lt;br/&gt;Data)] --&gt; B((Are all&lt;br/&gt;vars the same&lt;br/&gt;scale/unit?))</span>
<span id="cb1-5"><a href="#cb1-5"></a>B --&gt; C((Yes))</span>
<span id="cb1-6"><a href="#cb1-6"></a>B --&gt; D((No))</span>
<span id="cb1-7"><a href="#cb1-7"></a>D -.- |Standardize&lt;br/&gt;Data| E(Estimate&lt;br/&gt;Sample&lt;br/&gt;Mean&lt;br/&gt;Vector)</span>
<span id="cb1-8"><a href="#cb1-8"></a>C --&gt; E</span>
<span id="cb1-9"><a href="#cb1-9"></a>D --&gt; F(Estimate&lt;br/&gt;Sample&lt;br/&gt;Mean&lt;br/&gt;Vector)</span>
<span id="cb1-10"><a href="#cb1-10"></a>E --&gt; G(Estimate&lt;br/&gt;Sample&lt;br/&gt;Covariance&lt;br/&gt;Matrix)</span>
<span id="cb1-11"><a href="#cb1-11"></a>F --&gt; H(Estimate&lt;br/&gt;Sample&lt;br/&gt;Correlation&lt;br/&gt;Matrix)</span>
<span id="cb1-12"><a href="#cb1-12"></a>G --&gt; I(Eigenvalues&lt;br/&gt;Eigenvectors)</span>
<span id="cb1-13"><a href="#cb1-13"></a>H --&gt; I</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<p>
</p><pre class="mermaid" data-tooltip-selector="#mermaid-tooltip-1">%%{init: {'theme': 'base', 'themeVariables': { 'background': '#FAFAF5', 'primaryColor': '#EAEAD6', 'nodeBorder': '#8B814C', 'lineColor': '#8B814C', 'primaryTextColor': '#191970', 'textColor': '#191970', 'fontSize': '12px', 'width': '100%'}}}%%

flowchart LR
A[(Clean&lt;br/&gt;Data)] --&gt; B((Are all&lt;br/&gt;vars the same&lt;br/&gt;scale/unit?))
B --&gt; C((Yes))
B --&gt; D((No))
D -.- |Standardize&lt;br/&gt;Data| E(Estimate&lt;br/&gt;Sample&lt;br/&gt;Mean&lt;br/&gt;Vector)
C --&gt; E
D --&gt; F(Estimate&lt;br/&gt;Sample&lt;br/&gt;Mean&lt;br/&gt;Vector)
E --&gt; G(Estimate&lt;br/&gt;Sample&lt;br/&gt;Covariance&lt;br/&gt;Matrix)
F --&gt; H(Estimate&lt;br/&gt;Sample&lt;br/&gt;Correlation&lt;br/&gt;Matrix)
G --&gt; I(Eigenvalues&lt;br/&gt;Eigenvectors)
H --&gt; I

</pre>
<div id="mermaid-tooltip-1" class="mermaidTooltip">

</div>
<p></p>
</div>
</div>
</div>
<section id="assumptions" class="level3">
<h3 data-anchor-id="assumptions">Assumptions</h3>
<ul>
<li>Variables should be continuous, interval or ratio level of measurement (ordinal variables, such as likert-scale, are also often used)</li>
<li>Variables should all be the same scale/units (<a href="#eq-stdzData">Equation&nbsp;1</a>)</li>
<li>Variables are linearly related - visually check scatter plot matrices (see <a href="#sec-linearity">Section&nbsp;3.2.2</a> for an example)</li>
<li>Outliers &amp; missing or impossible values should be removed (see <a href="#sec-cleanData">Section&nbsp;3.2.1</a> for an example)</li>
</ul>
</section>
<section id="sample-data" class="level3">
<h3 data-anchor-id="sample-data">Sample Data</h3>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  overflow:hidden;padding:10px 8px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  font-weight:normal;overflow:hidden;padding:10px 8px;word-break:normal;}
.tg .tg-vi6l{background-color:#ffffff;border-color:#8b814c;color:#8b814c;text-align:center;vertical-align:top}
.tg .tg-pi0b{background-color:#eaead6;border-color:#8b814c;color:#8b814c;font-weight:bold;text-align:center;vertical-align:top}
</style>

<table class="tg" style="undefined;table-layout: fixed; width: 791px">
<colgroup>
<col style="width: 126px">
<col style="width: 111px">
<col style="width: 111px">
<col style="width: 111px">
<col style="width: 111px">
<col style="width: 111px">
<col style="width: 111px">
</colgroup>
<thead>
<tr>
<th class="tg-pi0b">
</th>
<th class="tg-pi0b">
<span class="math inline">\(X_1\)</span>
</th>
<th class="tg-pi0b">
<span class="math inline">\(X_2\)</span>
</th>
<th class="tg-pi0b">
…
</th>
<th class="tg-pi0b">
<span class="math inline">\(X_j\)</span>
</th>
<th class="tg-pi0b">
…
</th>
<th class="tg-pi0b">
<span class="math inline">\(X_p\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-pi0b">
<span class="math inline">\(x_1\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{11}\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{12}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{1j}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{1p}\)</span>
</td>
</tr>
<tr>
<td class="tg-pi0b">
<span class="math inline">\(x_2\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{21}\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{22}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{2j}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{2p}\)</span>
</td>
</tr>
<tr>
<td class="tg-pi0b">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
</tr>
<tr>
<td class="tg-pi0b">
<span class="math inline">\(x_i\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{i1}\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{i2}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{ij}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{ip}\)</span>
</td>
</tr>
<tr>
<td class="tg-pi0b">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
…
</td>
</tr>
<tr>
<td class="tg-pi0b">
<span class="math inline">\(x_n\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{n1}\)</span>
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{n2}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{nj}\)</span>
</td>
<td class="tg-vi6l">
…
</td>
<td class="tg-vi6l">
<span class="math inline">\(x_{np}\)</span>
</td>
</tr>
</tbody>

</table>
</section>
<section id="equations" class="level3">
<h3 data-anchor-id="equations">Equations</h3>
<p><strong>Standardized Data:</strong> <span id="eq-stdzData"><span class="math display">\[{z_{ij}}\ =\ \frac{{x_{ij}} - {\overline{x_j}}} {\sqrt{\hat{\sigma_{jj}}}}, \ \ \ \ \ where\ \ \ \ i\ =\ \{1,2,...,n\}, \ \ \ \ j\ =\ \{1,2,...,p\} \tag{1}\]</span></span></p>
<p><strong>Random Vector:</strong> <span id="eq-randomVector"><span class="math display">\[{x_i} = {({x_{i1}}, ... , {x_{ip}})}^T,\ \ \ \ \ \ \ \ \ where\ \ i\ =\ \{1,2,...,n\} \tag{2}\]</span></span></p>
<p><strong>Sample Mean Vector:</strong> <span id="eq-meanVector"><span class="math display">\[\hat{\mu}\ \ =\ \ \overline{x}\ \ =\ \ \frac{1}{n} \sum_{i=1}^{n} x_i \tag{3}\]</span></span></p>
<p><strong>Sample Covariance Matrix:</strong> <span id="eq-covMatrix"><span class="math display">\[\hat{\sum}\ \ =\ \ S\ \ =\ \ {(\hat{\sigma}_{ij})}_{p{\sf x}p}\ \ =\ \ \frac{1}{n-1} \sum_{i=1}^{n} {(x_i - \overline{x})(x_i - \overline{x})}^T \tag{4}\]</span></span></p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span style="color: #1A79E1; font-size:12px;">The <strong>sample mean vector</strong> represents the center of the random vector (<span class="math inline">\(x_i\)</span>)</span></p>
<p><span style="color: #1A79E1; font-size:12px;">The <strong>sample covariance matrix</strong> represents the variations (diagonal elements) &amp; correlations (off-diagonal elements) of the random vector (<span class="math inline">\(x_i\)</span>)</span></p>
</div>
</div>
</div>
<p><strong>Eigenvectors:</strong> <span id="eq-eigenvec"><span class="math display">\[{\hat{a}_{k}} \tag{5}\]</span></span></p>
<p><strong>Eigenvalues:</strong> <span id="eq-eigenval"><span class="math display">\[{\hat{y}_{ik}}\ =\ {\hat{a}^T_{k}}(x_i\ -\ \overline{x}),\ \ \ \ \ \ \ i\ =\ \{1,2,...,n\},\ \ \ \ \ \ \ k\ =\ \{1,2,...,p\} \tag{6}\]</span></span></p>
<p><br></p>
</section>
</section>
<section id="analysis-and-results" class="level2" data-number="3">
<h2 data-number="3" data-anchor-id="analysis-and-results"><span class="header-section-number">3</span> Analysis and Results</h2>
<section id="packages" class="level3">
<h3 data-anchor-id="packages">Packages</h3>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="fu">library</span>(data.table)</span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb2-5"><a href="#cb2-5"></a><span class="fu">library</span>(MASS)</span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">library</span>(paletteer)</span>
<span id="cb2-8"><a href="#cb2-8"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-9"><a href="#cb2-9"></a><span class="fu">library</span>(DescTools)</span>
<span id="cb2-10"><a href="#cb2-10"></a><span class="fu">library</span>(gt)</span>
<span id="cb2-11"><a href="#cb2-11"></a><span class="fu">library</span>(gridExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="data" class="level3">
<h3 data-anchor-id="data">Data</h3>
<p>Results of 2000 respondents answering a 5-point Likert scale of their belief in various conspiracies. Sampled from a nationally representative survey in 2011. (Replication data and code may be found at the AJPS Dataverse website - <a href="">https://thedata.harvard.edu/dvn/dv/ajps</a>) <span class="citation" data-cites="originalConspiracyData">(<a href="#ref-originalConspiracyData" role="doc-biblioref">Oliver and Wood 2013</a>)</span></p>
<p><strong>SCALE LEVELS:</strong></p>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
</style>

<table class="tg" style="undefined;table-layout: fixed; width: 258px">
<colgroup>
<col style="width: 163px">
<col style="width: 95px">
</colgroup>
<thead>
<tr>
<th class="tg-amwm">
Label
</th>
<th class="tg-amwm">
Level
</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tg-baqh">
Strongly Disagree
</td>
<td class="tg-baqh">
1
</td>
</tr>
<tr>
<td class="tg-baqh">
Disagree
</td>
<td class="tg-baqh">
2
</td>
</tr>
<tr>
<td class="tg-baqh">
Neither
</td>
<td class="tg-baqh">
3
</td>
</tr>
<tr>
<td class="tg-baqh">
Agree
</td>
<td class="tg-baqh">
4
</td>
</tr>
<tr>
<td class="tg-baqh">
Strongly Agree
</td>
<td class="tg-baqh">
5
</td>
</tr>
</tbody>

</table>
<p><strong>VARIABLES:</strong></p>
<ul>
<li><strong>truther911:</strong> Certain U.S. government officials planned the attacks of September 11, 2001, because they wanted the United States to go to war in the Middle East.</li>
<li><strong>obamabirth:</strong> President Barack Obama was not really born in the United States and does not have an authentic Hawaiian birth certificate.</li>
<li><strong>fincrisis:</strong> The current financial crisis was secretly orchestrated by a small group of Wall Street bankers to extend the power of the Federal Reserve and further their control of the world’s economy.</li>
<li><strong>flourolights:</strong> The U.S. government is mandating the switch to compact fluorescent light bulbs because such lights make people more obedient and easier to control.</li>
<li><strong>endtimes:</strong> We are currently living in End Times as foretold by Biblical prophecy.</li>
<li><strong>sorosplot:</strong> Billionaire George Soros is behind a hidden plot to destabilize the American government, take control of the media, and put the world under his control.</li>
<li><strong>iraqjews:</strong> The U.S. invasion of Iraq was not part of a campaign to fight terrorism, but was driven by oil companies and Jews in the U.S. and Israel.</li>
<li><strong>vaportrail:</strong> Vapor trails left by aircraft are actually chemical agents deliberately sprayed in a clandestine program directed by government officials.</li>
</ul>
<p><strong>GROUPING FACTOR (y = political ideology):</strong></p>
<ul>
<li>Very Liberal</li>
<li>Liberal</li>
<li>Somewhat Liberal</li>
<li>Middle of the Road</li>
<li>Somewhat Conservative</li>
<li>Conservative</li>
<li>Very Conservative</li>
</ul>
<section id="sec-cleanData" class="level4">
<h4 data-anchor-id="sec-cleanData">Read &amp; Clean Data</h4>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="co"># READ DATA FROM A GITHUB CSV FILE</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>conspiracy<span class="ot">&lt;-</span> (<span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/bjcarr08/sampleData/main/kaggleConspiracyTheoriesData.csv"</span>, <span class="at">stringsAsFactors =</span> T))[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a><span class="co"># REMOVE ROWS WITH NAs &amp; IMPOSSIBLE VALUES (removed rows where participant marked 'not sure' as political ideology)</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>conspiracy<span class="ot">&lt;-</span> conspiracy[<span class="fu">complete.cases</span>(conspiracy),] <span class="sc">%&gt;%</span> <span class="fu">filter</span>(y<span class="sc">!=</span><span class="st">"Not Sure"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-codefold="hide">
<div class="cell-output cell-output-stdout">
<pre><code>png 
  2 </code></pre>
</div>
</div>
</section>
<section id="sec-linearity" class="level4">
<h4 data-anchor-id="sec-linearity">Visualize Data</h4>
<p>Visually checking if linearity between variables assumption is met (not a strictly help assumption, especially when using ordinal data).</p>
<p>The correlation matrix plots show enough of a relationship between variables to meet the assumption of linearity.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># SCATTER PLOT MATRICES: TO CHECK LINEARITY ASSUMPTION</span></span>
<span id="cb5-2"><a href="#cb5-2"></a><span class="fu">par</span>(<span class="at">col.axis=</span><span class="st">"#8B814C"</span>,<span class="at">col.lab=</span><span class="st">"#8B814C"</span>,<span class="at">col.main=</span><span class="st">"#8B814C"</span>,<span class="at">col.sub=</span><span class="st">"#8B814C"</span>,<span class="at">pch=</span><span class="dv">20</span>, <span class="at">col=</span><span class="st">"#8B814C"</span>, <span class="at">bg=</span><span class="st">"transparent"</span>)</span>
<span id="cb5-3"><a href="#cb5-3"></a>DescTools<span class="sc">::</span><span class="fu">PlotPairs</span>(<span class="fu">sapply</span>(conspiracy[,<span class="sc">-</span><span class="dv">9</span>], <span class="cf">function</span>(x) <span class="fu">jitter</span>(x, <span class="dv">5</span>)), </span>
<span id="cb5-4"><a href="#cb5-4"></a>                     <span class="at">g=</span>conspiracy<span class="sc">$</span>y,</span>
<span id="cb5-5"><a href="#cb5-5"></a>                     <span class="at">col=</span><span class="fu">alpha</span>(<span class="st">"#8B814C"</span>, <span class="fl">0.1</span>), </span>
<span id="cb5-6"><a href="#cb5-6"></a>                     <span class="at">col.smooth=</span><span class="st">"#8B814C"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot0-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># TRANSFORM TO LONG DATA FOR PLOTS</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>conspiracy.Long<span class="ot">&lt;-</span> conspiracy <span class="sc">%&gt;%</span> <span class="fu">pivot_longer</span>(<span class="sc">!</span>y, <span class="at">names_to=</span><span class="st">"conspiracy"</span>, <span class="at">values_to=</span><span class="st">"score"</span>, <span class="at">values_transform=</span><span class="fu">list</span>(<span class="at">score=</span>as.numeric))</span>
<span id="cb6-3"><a href="#cb6-3"></a></span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="co"># HISTOGRAMS</span></span>
<span id="cb6-5"><a href="#cb6-5"></a><span class="fu">ggplot</span>(conspiracy.Long, <span class="fu">aes</span>(score, <span class="at">fill=</span>conspiracy, <span class="at">color=</span>conspiracy)) <span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>  <span class="fu">geom_histogram</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">5</span>,<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7"></a>  lemon<span class="sc">::</span><span class="fu">facet_rep_wrap</span>(.<span class="sc">~</span>conspiracy, <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">labeller=</span><span class="st">"label_both"</span>, <span class="at">repeat.tick.labels=</span>T) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Distributions of Raw Score"</span>) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb6-11"><a href="#cb6-11"></a>        <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>),</span>
<span id="cb6-12"><a href="#cb6-12"></a>        <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#EAEAD6"</span>, <span class="at">color =</span> <span class="st">"#8B814C"</span>),</span>
<span id="cb6-13"><a href="#cb6-13"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size=</span><span class="dv">14</span>),</span>
<span id="cb6-14"><a href="#cb6-14"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAF5"</span>),</span>
<span id="cb6-15"><a href="#cb6-15"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>),</span>
<span id="cb6-16"><a href="#cb6-16"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size=</span><span class="dv">14</span>),</span>
<span id="cb6-17"><a href="#cb6-17"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size=</span><span class="dv">14</span>),</span>
<span id="cb6-18"><a href="#cb6-18"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot1-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
<p>Looking at the distribution plots above, we can see that all variables are measured in the same scale/units &amp; do not need to be standardized.</p>
</section>
</section>
<section id="pca" class="level3">
<h3 data-anchor-id="pca">PCA</h3>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">options</span>(<span class="at">width =</span> <span class="dv">100</span>)</span>
<span id="cb7-2"><a href="#cb7-2"></a></span>
<span id="cb7-3"><a href="#cb7-3"></a><span class="co"># STANDARDIZE DATA [SKIP]</span></span>
<span id="cb7-4"><a href="#cb7-4"></a><span class="co">#conspiracy&lt;- conspiracy %&gt;% mutate(across(.cols=truther911:vaportrail, scale))</span></span>
<span id="cb7-5"><a href="#cb7-5"></a></span>
<span id="cb7-6"><a href="#cb7-6"></a><span class="co"># RE-LEVEL POLITICAL IDEOLOGY (Very Liberal - Very Conservative)</span></span>
<span id="cb7-7"><a href="#cb7-7"></a>conspiracy<span class="sc">$</span>y<span class="ot">&lt;-</span> <span class="fu">factor</span>(conspiracy<span class="sc">$</span>y, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Very Liberal"</span>, <span class="st">"Liberal"</span>, <span class="st">"Somewhat Liberal"</span>, <span class="st">"Middle of the Road"</span>, <span class="st">"Somewhat Conservative"</span>, <span class="st">"Conservative"</span>, <span class="st">"Very Conservative"</span>))</span>
<span id="cb7-8"><a href="#cb7-8"></a></span>
<span id="cb7-9"><a href="#cb7-9"></a><span class="co"># RE-NAMED VARIABLE 'y'</span></span>
<span id="cb7-10"><a href="#cb7-10"></a><span class="fu">names</span>(conspiracy)[<span class="dv">9</span>]<span class="ot">&lt;-</span> <span class="st">"PoliticalIdeology"</span></span>
<span id="cb7-11"><a href="#cb7-11"></a></span>
<span id="cb7-12"><a href="#cb7-12"></a><span class="co"># DATA FOR PCA FUNCTION (only keep numeric variables)</span></span>
<span id="cb7-13"><a href="#cb7-13"></a>df<span class="ot">&lt;-</span> conspiracy[,<span class="sc">-</span><span class="dv">9</span>]</span>
<span id="cb7-14"><a href="#cb7-14"></a></span>
<span id="cb7-15"><a href="#cb7-15"></a><span class="co"># PCA</span></span>
<span id="cb7-16"><a href="#cb7-16"></a><span class="co">#pc1&lt;- prcomp(df, scale.=T)</span></span>
<span id="cb7-17"><a href="#cb7-17"></a>pc1<span class="ot">&lt;-</span> <span class="fu">prcomp</span>(df)</span>
<span id="cb7-18"><a href="#cb7-18"></a></span>
<span id="cb7-19"><a href="#cb7-19"></a><span class="fu">summary</span>(pc1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Importance of components:
                          PC1    PC2     PC3    PC4     PC5     PC6     PC7     PC8
Standard deviation     2.2922 1.5820 1.05878 0.9088 0.88231 0.85821 0.80225 0.69443
Proportion of Variance 0.4256 0.2027 0.09081 0.0669 0.06306 0.05966 0.05214 0.03907
Cumulative Proportion  0.4256 0.6284 0.71917 0.7861 0.84913 0.90880 0.96093 1.00000</code></pre>
</div>
</div>
<p>From the table directly above (Importance of components), we are mainly focused on the first 2 columns or principal components. Looking at the second row in the table, Proportion of Variance, the first PC accounts for about 43% of total variation &amp; the second PC accounts for about 20%, with the rest of the PC’s each accounting for about 9% or less. To use PCA, the threshold for Cumulative Proportion is usually at least 70%-80%, but this is just a guideline as there are no set rules.</p>
<section id="scree-plot" class="level4">
<h4 data-anchor-id="scree-plot">Scree-Plot</h4>
<p>This plot visually represents the ‘Proportion of Variance’ from the previous table. Here it is easy to see the drop off after the second PC. This type of plot can be used to help decide how many PC’s should be used/kept.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">par</span>(<span class="at">col.axis=</span><span class="st">"#8B814C"</span>,<span class="at">col.lab=</span><span class="st">"#8B814C"</span>,<span class="at">col.main=</span><span class="st">"#8B814C"</span>,<span class="at">col.sub=</span><span class="st">"#8B814C"</span>,<span class="at">pch=</span><span class="dv">20</span>, <span class="at">col=</span><span class="st">"#8B814C"</span>, <span class="at">bg=</span><span class="st">"transparent"</span>)</span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">screeplot</span>(<span class="fu">princomp</span>(df), <span class="at">type=</span><span class="st">"lines"</span>, <span class="at">bg=</span><span class="st">"transparent"</span>, <span class="at">col=</span><span class="st">"#8B814C"</span>, <span class="at">main=</span><span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot2-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
</section>
<section id="biplot" class="level4">
<h4 data-anchor-id="biplot">Biplot</h4>
<p>In this plot we see the eigenvectors (points) &amp; eigenvalues (arrows). PCA can only be interpreted in either the x direction (horizontal distances) or in the y direction (vertical distances), but not both. Although the first PC is about 43% of variance, there is no distinction between political ideology groups in the horizontal plane. But, we do see a pattern in the vertical direction, specifically obamabirth &amp; sorosplot consisting of more conservative ideology, and iraqjews and truther911 with more liberal ideology.</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a><span class="fu">autoplot</span>(pc1,</span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="co"># AUTOPLOT OPTIONS</span></span>
<span id="cb10-3"><a href="#cb10-3"></a>  <span class="at">data=</span>conspiracy, </span>
<span id="cb10-4"><a href="#cb10-4"></a>  <span class="at">colour=</span><span class="st">"PoliticalIdeology"</span>, </span>
<span id="cb10-5"><a href="#cb10-5"></a>  <span class="at">loadings=</span>T, <span class="at">loadings.colour=</span><span class="fu">alpha</span>(<span class="st">"#191970"</span>, <span class="fl">0.5</span>), </span>
<span id="cb10-6"><a href="#cb10-6"></a>  <span class="at">loadings.label=</span>T, <span class="at">loadings.label.colour=</span><span class="st">"#191970"</span>, <span class="at">loadings.label.size=</span><span class="dv">5</span>, <span class="at">loadings.label.hjust=</span><span class="dv">0</span>) <span class="sc">+</span> </span>
<span id="cb10-7"><a href="#cb10-7"></a>  <span class="co"># CUSTOM COLORS FOR POLITICAL IDEOLOGY GROUPS</span></span>
<span id="cb10-8"><a href="#cb10-8"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">alpha</span>(<span class="fu">paletteer_d</span>(<span class="st">"rcartocolor::Temps"</span>), <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9"></a>  <span class="co"># GGPLOT THEME OPTIONS</span></span>
<span id="cb10-10"><a href="#cb10-10"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11"></a>  <span class="fu">theme</span>(<span class="at">legend.key =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAF5"</span>),</span>
<span id="cb10-12"><a href="#cb10-12"></a>        <span class="at">legend.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAF5"</span>),</span>
<span id="cb10-13"><a href="#cb10-13"></a>        <span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb10-14"><a href="#cb10-14"></a>        <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size =</span> <span class="dv">16</span>),</span>
<span id="cb10-15"><a href="#cb10-15"></a>        <span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>),</span>
<span id="cb10-16"><a href="#cb10-16"></a>        <span class="at">plot.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"#FAFAF5"</span>),</span>
<span id="cb10-17"><a href="#cb10-17"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size =</span> <span class="dv">14</span>),</span>
<span id="cb10-18"><a href="#cb10-18"></a>        <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>, <span class="at">size =</span> <span class="dv">16</span>),</span>
<span id="cb10-19"><a href="#cb10-19"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"#8B814C"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot3-1.png" class="img-fluid" width="1152"></p>
</div>
</div>
</section>
<section id="loadings" class="level4">
<h4 data-anchor-id="loadings">Loadings</h4>
<p>The matrix of variable loadings (i.e., a matrix whose columns contain the eigenvectors).</p>
<div class="cell">
<details open="">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>(<span class="fu">princomp</span>(df))<span class="sc">$</span>loadings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
             Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8
truther911    0.334  0.460  0.103  0.462  0.169  0.239  0.598       
obamabirth    0.393 -0.545  0.415  0.519 -0.198 -0.217 -0.135       
fincrisis     0.340  0.270  0.194 -0.166 -0.496  0.588 -0.383       
fluorolights  0.354               -0.134  0.650        -0.420  0.499
endtimes      0.396 -0.245 -0.855  0.102 -0.170                     
sorosplot     0.371 -0.361  0.211 -0.645                0.508       
iraqjews      0.288  0.436        -0.211 -0.355 -0.688         0.287
vaportrail    0.340  0.191                0.326 -0.242 -0.204 -0.799

               Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8
SS loadings     1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000
Proportion Var  0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125
Cumulative Var  0.125  0.250  0.375  0.500  0.625  0.750  0.875  1.000</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="conclusion" class="level2" data-number="4">
<h2 data-number="4" data-anchor-id="conclusion"><span class="header-section-number">4</span> Conclusion</h2>
<p>PCA is a very powerful tool for data analysis. It allows us to see patterns and trends hidden in large sets of data that would otherwise be very difficult to make out. PCA is also very flexible in its application which is why it sees use in so many different fields. This flexibility has also led to many different adaptations of the method, each with its own variations added to adapt to the task at hand. Large data sets are extremely common amongst many different fields of study. Principal component analysis requires no assumption of a distribution and can be applied to many types of numerical data. We focus on the Assumptions we ensure the variables are continuous, intervals or ratio levels of measurements are also of the same scale and units. We also make sure in our dataset that the variables are linearly related, and we use the scatterplot to check the variables. Lastly, we ensure Outliers are removed and those Null values that are missing are noted and removed. In our conclusion of Data, we saw that Scree-plot Proportion of Variance 0.4256 0.2027 0.09081 0.0669 0.06306 0.05966 0.05214 0.03907 and as well that plot dropped 10% from variances after Comp 3. Lastly we noticed that the PCA can CA can only be interpreted in either the x direction (horizontal distances) or in the y direction (vertical distances), but not both but not diagonally</p>
<p>PCA can map the principal components to a 2-D plane and create a cluster we can visualize and use to analyze the data set. We can also just focus on the principal components themselves and draw conclusions from them when visualization is not a valid option. PCA’s strength is that it retains as much variance in the data as possible while increasing the interpretability of the data and while it is sensitive to scaling it remains a very useful method of analysis. PCA has been found to be useful when performing k-means clustering which by itself is a clustering method with countless applications. With all of the flexibility and usefulness of PCA taken into consideration it is easy to see why it is such a popular way to analyze large data sets across so many fields. As long as there are large data sets there will be a demand to reduce the dimension of that data and make valid interpretations about the trends present in that data, to this end we have PCA. <span class="citation" data-cites="Richardson">(<a href="#ref-Richardson" role="doc-biblioref">Richardson 2009</a>)</span></p>
</section>
<section id="references" class="level2 unnumbered bibliography" style="background-color: #FAFAF5; color: #8B814C" data-number="5">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">5 References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Camargo" class="csl-entry" role="doc-biblioentry">
A, Camargo. 2022. <span>“PCAtest: Testing the Statistical Significance of Principal Component Analysis in r.”</span> <em>PeerJ</em>. <a href="https://doi.org/10.7717/peerj.12967">https://doi.org/10.7717/peerj.12967</a>.
</div>
<div id="ref-Alkha" class="csl-entry" role="doc-biblioentry">
Alkhayrat, Maha, Mohamad Aljnidi, and Kadan Aljoumaa. 2020. <span>“A Comparative Dimensionality Reduction Study in Telecom Customer Segmentation Using Deep Learning and PCA.”</span> <em>Journal of Big Data</em> 7 (February): 9. <a href="https://doi.org/10.1186/s40537-020-0286-0">https://doi.org/10.1186/s40537-020-0286-0</a>.
</div>
<div id="ref-Cao2018" class="csl-entry" role="doc-biblioentry">
Cao, Wen, Nicholas Czarnek, Juan Shan, and Lin Li. 2018. <span>“Microaneurysm Detection Using Principal Component Analysis and Machine Learning Methods.”</span> <em>IEEE Transactions on NanoBioscience</em> 17 (3): 191–98. <a href="https://doi.org/10.1109/TNB.2018.2840084">https://doi.org/10.1109/TNB.2018.2840084</a>.
</div>
<div id="ref-Gorg2021" class="csl-entry" role="doc-biblioentry">
Gorgoglione, Angela, Alberto Castro, V. Iacobellis, and Gioia Andrea. 2021. <span>“A Comparison of Linear and Non-Linear Machine Learning Techniques (PCA and SOM) for Characterizing Urban Nutrient Runoff.”</span> <em>Sustainability</em> 13 (February): 2054. <a href="https://doi.org/10.3390/su13042054">https://doi.org/10.3390/su13042054</a>.
</div>
<div id="ref-Jolliffe" class="csl-entry" role="doc-biblioentry">
Jolliffe IT, Cadima J. 2016. <span>“Principal Component Analysis: A Review and Recent Developments.”</span> <em>Philosophical Transactions A</em>.
</div>
<div id="ref-Jones" class="csl-entry" role="doc-biblioentry">
Jones, Payton, Patrick Mair, and Richard McNally. 2018. <span>“Visualizing Psychological Networks: A Tutorial in r.”</span> <em>Frontiers in Psychology</em> 9 (September). <a href="https://doi.org/10.3389/fpsyg.2018.01742">https://doi.org/10.3389/fpsyg.2018.01742</a>.
</div>
<div id="ref-lang2021applied" class="csl-entry" role="doc-biblioentry">
Lang, WU, and Jin Qiu. 2021. <em>Applied Multivariate Statistical Analysis and Related Topics with r</em>. edp sciences.
</div>
<div id="ref-originalConspiracyData" class="csl-entry" role="doc-biblioentry">
Oliver, J. Eric, and Thomas J. Wood. 2013. <span>“<span class="nocase">Replication data for: Conspiracy Theories and the Paranoid Style(s) of Mass Opinion</span>.”</span> Harvard Dataverse. <a href="https://doi.org/10.7910/DVN/22976">https://doi.org/10.7910/DVN/22976</a>.
</div>
<div id="ref-Richardson" class="csl-entry" role="doc-biblioentry">
Richardson, M. 2009. <span>“Principal Component Analysis.”</span>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
</div> <!-- /content -->



<script src="index_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>