---
title: "Prinicpal Component Analysis"
format: 
  revealjs:
    theme: dark
editor: visual
---

## What is it?

- Principal component analysis (PCA) is an unsupervised machine learning method
that can be used as the first step in data analysis
-   Main goal: reduce the number of
dimensions/features while retaining most of the original variability
-   This is achieved using a vector space transform

## Why use PCA?

- Makes it easier to graphically visualize hidden patterns in the data
- High number of predictor variables or highly correlated variables when running a
regression model
- To observe hidden trends, jumps, clusters, patterns and outliers
- PCA assumes no distribution in data in a descriptive context
- Widely adaptive as an exploratory method across disciplines and data types

## Where has PCA been applied?

- PCA is a broadly used statistical method whose use stretches across many 
scientific disciplines
- Image analysis, analysis of web data, cyber security analysis, 
mental disorders, recognizing microanerysm, facial recognition, etc. 
- Many different adaptations of PCA have been developed based on the variation in goals and
data types associated with each respective discipline

## How does it work?
- By mathematical projection we can interpret the original data set with just a 
few variables, namely the principal components
- The process of reduction preserves the maximum variability in the data (i.e. the statistical information present in the data)
- "...find new variables that are linear functions of those in the original data set, that
successively maximize variance and that are uncorrelated with each other" [@Jolliffe]

## Code

```{r}



```

## End